name: Update Phar

on:
  push:
    branches: [ $default-branch, phar ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with Phar extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: phar
          ini-values: phar.readonly = Off

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # mandatory using --ignore-platform-reqs option
      # because required ast extension is not installed
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-progress --ignore-platform-reqs

      - name: Download phar-composer.phar
        run: curl -sLo /usr/local/bin/phar_composer.phar "https://github.com/clue/phar-composer/releases/download/v1.4.0/phar-composer-1.4.0.phar"

      - name: Update Phar file
        run: php /usr/local/bin/phar_composer.phar build

      - name: Push updated Phar file
        uses: EndBug/add-and-commit@v8
        with:
          add: elephoot.phar
          author_name: GitHub Actions
          message: Update Phar